
# services:
#   node-app:
#     container_name: express-node-app-container
#     ports:
#       - "4000:4000"
#     environment:
#       - NODE_ENV=production
#     env_file:
#       - ./.env

services:
  node-app:
    build:
    target: production
    environment:
      - NODE_ENV=production
    command: npm start

 